# Basic settings for GitHub Pages with clean URLs
title: Casey McCollum
description: Casey McCollum's portfolio website - Video producer & international relations student
url: https://caseymc.com
baseurl: "" # Leave empty if your site is in the root, otherwise add your sub-path

# Enable clean URLs without .html extension
permalink: pretty

# GitHub Pages settings
github: [metadata]

# Default layout if you're using Jekyll
defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - README.md
  - .gitignore